### ISSUE TITLE
Indentation size and sorting

### ISSUE THREAD

**Issue by kseistrup** [tidwall/pretty#1]
Perhaps it would be useful with two optional parameters: sort (boolean) and indent (integer or string).

A version of the example with indentation=2 and sorted keys could look like this:

```json
{
  "age": 37,
  "children": [
    "Sara",
    "Alex",
    "Jack"
  ],
  "fav.movie": "Deer Hunter",
  "friends": [
    {
      "age": 44,
      "first": "Janet",
      "last": "Murphy"
    }
  ],
  "name": {
    "first": "Tom",
    "last": "Anderson"
  }
}
```

**Comment by tidwall** [comment]
Thanks for the suggestion. Sorting would be a nice option. 

Right now there's a `PrettyOptions(json, opt)` function that allows for providing the indentation and also the max-width for single line arrays.

**Comment by tidwall** [comment]
I just pushed an update that allows for sorting keys on objects.
