### ISSUE TITLE
Sorting key-value pairs is inconsistent with duplicate keys

### ISSUE THREAD

**Issue by leighmcculloch** [tidwall/pretty#10]
Sorting key-value pairs is inconsistent with duplicate keys.

For example the following two JSONs when pretty'd will result differently:

1 –
```json
{"key":"value","key":"value2","key3":3}
```
```json
{
 "key": "value",
 "key": "value2",
 "key3": 3
}
```

2 –
```json
 {
				"key":"value2",
				"key":"value",
				"key3": 3
			}
```
```json
{
 "key": "value2",
 "key": "value",
 "key3": 3
}
```

This maybe is an acceptable limitation since duplicate keys are not commonly accepted by JSON parsing libraries, or at the least are reduced to a single value. But the JSON format doesn't disallow duplicate keys, and it is difficult to normalize output like the output I have when the key-pairs as a whole are not sorted and only the key.

I'm not sure if it is reasonable to expect to sort on key-pair given that would require sorting on any value type including objects and arrays. A method for sorting all values would need to be derived.

I'd be open to attempting a contribution if such a feature would be accepted.

**Comment by tidwall** [comment]
I agree that this should be fixed. At the very least it should use a stable sort, but it would be great if it also compared the values when the keys are equal. 

Changing the current Less function into something like:

```
{
     if keyA < keyB {
         return true
     }
     if keyA > keyB {
          return false
     }
     return valA < valB
}
```

The challenge I see with comparing the values is the different JSON types. The `gjson` project has a [Less](https://godoc.org/github.com/tidwall/gjson#Result.Less) function for this purpose, but since `gjson` uses the `pretty` package, we'd need to pull the logic directly into `pretty`.

**Comment by tidwall** [comment]
I'd be happy if you attempted a PR. :)

**Comment by leighmcculloch** [comment]
Thanks @tidwall !!!

**Comment by tidwall** [comment]
you're welcome

**Comment by leighmcculloch** [comment]
I discovered the new sorting appears to sort the following inputs differently.

Input:
```json
{"key":"abc","key":"value","key3":3}
```
Output:
```json
{
  "key": "abc",
  "key": "value",
  "key3": 3
}
```

Input:
```json
 {
				"key":"value",
				"key":"abc",
				"key3": 3
			}
```
Output:
```json
{
  "key": "value",
  "key": "abc",
  "key3": 3
}
```

Not sure what is happening yet. I'm using `v1.1.0`.

**Comment by tidwall** [comment]
I just pushed a fix.

What happening was the previously new sorting compared keys, then if equal, compared value **positions** relative to the json document. That worked to ensure that the duplicate keys kept "stable" order. But was not taking into account the actual contents of the value.

This newest sorting performs an actual comparison of the values.

**Comment by leighmcculloch** [comment]
It works!

That was a fast fix! Thanks1
