### ISSUE TITLE
Whitespace in multi-line arrays

### ISSUE THREAD

**Issue by mbrancato** [tidwall/pretty#11]
I noticed that it appears to add a space after commas in arrays of objects. Most beautifiers wouldn't include a space after a comma and before a newline.

e.g.
```json
[
  {
    "foo": 1
  }, 
  {
    "bar": 0
  }
]
```

vs.

```json
[
  {
    "foo": 1
  },
  {
    "bar": 0
  }
]
```

**Comment by tidwall** [comment]
I agree. I just pushed an update.
