### ISSUE TITLE
NaN support

### ISSUE THREAD

**Issue by glycerine** [tidwall/pretty#12]
Sadly, I can't use the standard lib "encoding/json" because it cannot support NaN pretty printing.

It would be lovely if "pretty" could handle NaN.

**Comment by tidwall** [comment]
AFAIK, NaN is not valid JSON.

**Comment by glycerine** [comment]
Agreed. Absolutely. But I still report numeric arrays that contain NaN in a JSON format.

**Comment by tidwall** [comment]
I just pushed an update that allows for `NaN` and `Inf` for pretty printing.

**Comment by glycerine** [comment]
🎆 Awesome. Thanks Josh!
