### ISSUE TITLE
Mixing and matching pretty and ugly output?

### ISSUE THREAD

**Issue by thisisaaronland** [tidwall/pretty#2]
Who's On First has a need to produce pretty-printed GeoJSON files with the _exception_ of actual geometries (which are also included at the end of the file) because they are often big and hard to look at.

Looking over the code for `pretty` (specifically the `appendPrettyAny` function) my sense is that teaching the code to toggle between "pretty" and "ugly" mode based on keys is more complicated than not. Possible but it would require a whole other can of logic to look ahead beyond the current byte.

Would you agree?

**Comment by tidwall** [comment]
Interesting problem. I agree the the logic with the current `pretty` is a bit complicated. It's primary designed to avoid allocation, lookaheads, and backtracking.

Perhaps you can use a combination of gjson and pretty. This is what I came up with:

https://gist.github.com/tidwall/ca6ca1dd0cb780f0be4d134f8e4eb7bc

It removes geometry from the feature, makes the feature pretty, uglyifies the geometry, and puts the geometry back in place.

**Comment by thisisaaronland** [comment]
Oh nice, thanks! I will give that a poke over the next couple of days.

**Comment by tidwall** [comment]
You're welcome
