### ISSUE TITLE
Function that accepts a JSON string from gjson and prints it

### ISSUE THREAD

**Issue by markerdmann** [tidwall/pretty#6]
It would be convenient if there was a function in the library that could do this directly:

`fmt.Println(string(pretty.Pretty([]byte(data.Raw))))`

Something along these lines:

`pretty.PPrint(data.Raw)`

If you're interesting in adding it, I'd be happy to submit a PR.

**Comment by tidwall** [comment]
I added a handy [@pretty](https://github.com/tidwall/gjson#modifiers-and-path-chaining) modifier in gjson for this purpose.

```
fmt.Println(data.Get("@pretty"));
```
