### ISSUE TITLE
Color: highlight escaped characters in strings

### ISSUE THREAD

**Issue by dolmen** [tidwall/pretty#7]
Highlight escaped characters in strings with a different color.

Exemple (using [goeval](https://github.com/dolmen-go/goeval)):
```
$ goeval -i fmt -i github.com/tidwall/pretty 'fmt.Println(string(pretty.Color([]byte(`"abc\u0020def\nghi"`), nil)))'
```
I expect `\u0020` and `\n` to be colored differently than the rest of the string. Suggestion: magenta.

**Comment by tidwall** [comment]
sounds good. I just pushed and update.
